name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Change 'main' to your primary branch name if different.

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16" # Change to the version you need.

            - name: Install Dependencies
              run: npm install

            - name: Build Project
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public # Change './public' if the publish directory is different.
